server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: 1234
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
